### PR TITLE
Remove sorting in find_perfect_hash_seed

### PR DESCRIPTION
**Pull request by tekknolagi**
This improves startup of a small Python file by 1.35% (instruction count from Callgrind) for me.

### CODE REVIEW

**Comment by blueloveTH** [comment]
Okaaaay! Thanks.
This place is under test and subject to change. So I think there is no need to do optimization now...

**Comment by blueloveTH** [comment]
If one want to do optimize, he can also remove `sort` because I just want the max value. But I use `sort` just because it is easy to do prototype and clear (not fast).

**Comment by tekknolagi** [comment]
Yeah, reading this a bit more, I understood what you were trying to do. I have a local patch to remove the `sort` completely.

**Comment by tekknolagi** [comment]
The new commit is an additional 3.6% win.

**Comment by tekknolagi** [comment]
It looks like this is also happening a lot because the stdlib modules are eagerly constructed. I wonder if it is possible to instead just register callbacks to load them on `import`.

**Comment by tekknolagi** [comment]
And maybe pre-compile the text modules as part of the build step?

**Comment by tekknolagi** [comment]
It looks like you already kind of merged this without mentioning the issue, so not sure how relevant this change is anymore.

**Pull request closed without merging**
