### PR TITLE
Implement deque in C++ as required by #139

### PR DESCRIPTION
**Pull request by numan947**
I have completed the initial integration of a blank deque class in the project. Right now, it's possible to run the following code to print a Hello World message as a dummy.

```python
import collections

dd = collections.deque() 

dd.printHelloWorld()

```
I will be updating the implementation with a real `deque` soon.

### CODE REVIEW

**Comment by blueloveTH** [comment]
This is a good start point.

**Comment by blueloveTH** [comment]
I want to provide an undocumented information.

Since `deque` is a container of other python objects, it requires a magic method `_gc_mark() const ` in `PyDeque` to mark each inside objects.

**Comment by blueloveTH** [comment]
Well. I see you implement a linkedlist by hand. Why not `std::list`? It is much more reliable :/

**Comment by blueloveTH** [comment]
And I think this could leak memory.

```cpp
        vm->bind(type, "copy(self) -> deque",
                 [](VM *vm, ArgsView args)
                 {
                     PyDeque &self = _CAST(PyDeque &, args[0]);
                     PyDeque *newDeque = new PyDeque();
                     DequeNode *p = self.dequeItems->head->next;
                     while (p != self.dequeItems->tail)
                     {
                         newDeque->append(p->obj);
                         p = p->next;
                     }
                     return vm->heap.gcnew<PyDeque>(PyDeque::_type(vm), *newDeque);
                     //                                                  ^ may leak memory
                 });
```

**Comment by numan947** [comment]
> Well. I see you implement a linkedlist by hand. Why not `std::deque<PyObject*>`? It is much more reliable :/
> 
> Also `std::deque` is faster than a linkedlist because its special internal data structure.

I completely forgot that `std::deque` exists. I have been away from C/C++ STLs for a few years now. I will change the implementation. Thanks for pointing it out.

**Comment by numan947** [comment]
> And I think this could leak memory.
> 
> ```c++
>         vm->bind(type, "copy(self) -> deque",
>                  [](VM *vm, ArgsView args)
>                  {
>                      PyDeque &self = _CAST(PyDeque &, args[0]);
>                      PyDeque *newDeque = new PyDeque();
>                      DequeNode *p = self.dequeItems->head->next;
>                      while (p != self.dequeItems->tail)
>                      {
>                          newDeque->append(p->obj);
>                          p = p->next;
>                      }
>                      return vm->heap.gcnew<PyDeque>(PyDeque::_type(vm), *newDeque);
>                      //                                                  ^ may leak memory
>                  });
> ```

I don't know how to handle this specific case. I would've asked for help after completing the rest of the implementation.

**Review by blueloveTH — COMMENTED** [review]
I saw your question.

```cpp
void PyDeque::_gc_mark() const{
    for (PyObject* obj: dequeItems) {
        PK_OBJ_MARK(obj);
    }
}
```

**Comment by numan947** [comment]
@blueloveTH I am almost done with the implementation. I am stuck on how to implement a suitable constructor as described in the  [cpython documentation](https://docs.python.org/3/library/collections.html#collections.deque).


Here is the binding I am trying right now:

```C++
       vm->bind(type, "__init__(self, iterable=None, maxlen=None) -> None",
            [](VM *vm, ArgsView args)
            {
                     PyDeque &self = _CAST(PyDeque &, args[0]);
                     //args[1] is the iterable
                     //args[2] is the maxlen
                     //TODO: HANDLE MAXLEN CASE and ITERABLE CASE
                     return vm->None;
            });
```

However, when trying to use it from the deque class I am getting an error:

```Python
dq = collections.deque([1,2,3,4])

##ERROR##
Traceback (most recent call last):
  File "test.py", line 28
    dq = collections.deque([1,2,3,4])
TypeError: expected 1 arguments, got 2
```

I don't know what I am missing here. Also when trying to initialize with maxlen, I get another error:

```Python
dq = collections.deque([1,2,3,4], maxlen=30)
###ERROR
Traceback (most recent call last):
  File "test.py", line 28
    dq = collections.deque([1,2,3,4], maxlen=30)
TypeError: old-style native_func does not accept keyword arguments
```

Could you please help me understand what I am missing here? Arguments to the functions are working fine for other functions. It's only creating this issue for the constructor. How do I approach this?

**Comment by blueloveTH** [comment]
Remove this line.
```cpp
// vm->bind_default_constructor<PyDeque>(type);
```
And add a custom constructor, not `__init__` but `__new__`.
```cpp
vm->bind(type, "__new__(cls, iterable=None, maxlen=None)", [](VM* vm, ArgsView args){
    Type cls_t = PK_OBJ_GET(Type, args[0]);
    PyObject* iterable = args[1];
    PyObject* maxlen = args[2];
    return vm->heap.gcnew<PyDeque>(cls_t, <...>);
   // <...> are arguments that will be passed into `PyDeque`'s constructor
});
```

**Comment by blueloveTH** [comment]
And..this is unsafe to leave a *strong ref* on the stack. `*it` could be deleted when running other lines.
```cpp
PyObject *it = vm->py_iter(args[1]); // strong ref
```
You must use a lock to prevent GC before critical lines.
```cpp
auto _lock = vm->heap.gc_scope_lock();
```
---
Or..use `vm->py_list()` to convert the iterable into `List` forcefully. This may have an underlying data copy.

**Comment by numan947** [comment]
@blueloveTH Thank you very much for all the information you provided. 
Now the basics of the deque is completely implemented. However, as `deque` is a list like container, I think
we need container-ish methods such as reversed(d), addition (add two list = another list), etc.

I found some part of this requirement in the [documentation](https://docs.python.org/3/library/collections.html#collections.deque)
```
In addition to the above, deques support iteration, pickling, len(d), reversed(d), 
copy.copy(d), copy.deepcopy(d), membership testing  with the in operator, and subscript 
references such as d[0] to access the first element. 
Indexed access is O(1) at both ends but slows to O(n) in the middle. For fast random access, 
use lists instead.
Starting in version 3.5, deques support __add__(), __mul__(), and __imul__().
```
Is there a comprehensive list of such methods that I need to implement?

The `basic.md` file in the repository contains a list:

#### Unary operators

+ `__repr__`
+ `__str__`
+ `__hash__`
+ `__len__`
+ `__iter__`
+ `__next__`
+ `__json__`
+ `__neg__`
+ `__bool__` (unused)

#### Logical operators

+ `__eq__`
+ `__lt__`
+ `__le__`
+ `__gt__`
+ `__ge__`
+ `__contains__`

#### Binary operators

+ `__add__`
+ `__radd__`
+ `__sub__`
+ `__rsub__`
+ `__mul__`
+ `__rmul__`
+ `__truediv__`
+ `__floordiv__`
+ `__mod__`
+ `__pow__`
+ `__matmul__`
+ `__lshift__`
+ `__rshift__`
+ `__and__`
+ `__or__`
+ `__xor__`
+ `__invert__`

#### Indexer

+ `__getitem__`
+ `__setitem__`
+ `__delitem__`

#### Specials

+ `__new__`
+ `__init__`
+ `__call__`
+ `__divmod__`
+ `__enter__`
+ `__exit__`
+ `__name__`
+ `__all__`

which of these are relevant for deque?

**Comment by numan947** [comment]
> @blueloveTH Thank you very much for all the information you provided. Now the basics of the deque is completely implemented. However, as `deque` is a list like container, I think we need container-ish methods such as reversed(d), addition (add two list = another list), etc.
> 
> I found some part of this requirement in the [documentation](https://docs.python.org/3/library/collections.html#collections.deque)
> 
> ```
> In addition to the above, deques support iteration, pickling, len(d), reversed(d), 
> copy.copy(d), copy.deepcopy(d), membership testing  with the in operator, and subscript 
> references such as d[0] to access the first element. 
> Indexed access is O(1) at both ends but slows to O(n) in the middle. For fast random access, 
> use lists instead.
> Starting in version 3.5, deques support __add__(), __mul__(), and __imul__().
> ```
> 
> Is there a comprehensive list of such methods that I need to implement?
> 
> The `basic.md` file in the repository contains a list:
> 
> #### Unary operators
> * `__repr__`
> * `__str__`
> * `__hash__`
> * `__len__`
> * `__iter__`
> * `__next__`
> * `__json__`
> * `__neg__`
> * `__bool__` (unused)
> 
> #### Logical operators
> * `__eq__`
> * `__lt__`
> * `__le__`
> * `__gt__`
> * `__ge__`
> * `__contains__`
> 
> #### Binary operators
> * `__add__`
> * `__radd__`
> * `__sub__`
> * `__rsub__`
> * `__mul__`
> * `__rmul__`
> * `__truediv__`
> * `__floordiv__`
> * `__mod__`
> * `__pow__`
> * `__matmul__`
> * `__lshift__`
> * `__rshift__`
> * `__and__`
> * `__or__`
> * `__xor__`
> * `__invert__`
> 
> #### Indexer
> * `__getitem__`
> * `__setitem__`
> * `__delitem__`
> 
> #### Specials
> * `__new__`
> * `__init__`
> * `__call__`
> * `__divmod__`
> * `__enter__`
> * `__exit__`
> * `__name__`
> * `__all__`
> 
> which of these are relevant for deque?
> 
> Or another option is that, I can just add the operations that are available in the `list` class implemented in `pocketpy.cpp` file.

Nevermind I think I got the answer already. Here's a list of things supported in `python3`

```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> f = collections.deque([4,5])*5
>>> f
deque([4, 5, 4, 5, 4, 5, 4, 5, 4, 5])
>>> 4 in f
True
>>> f.
f.append(      f.copy(        f.extendleft(  f.maxlen       f.remove(      
f.appendleft(  f.count(       f.index(       f.pop(         f.reverse(     
f.clear(       f.extend(      f.insert(      f.popleft(     f.rotate(      
>>> f.__
f.__add__(            f.__eq__(             f.__init_subclass__(  f.__repr__()
f.__bool__()          f.__format__(         f.__iter__()          f.__reversed__(
f.__class__(          f.__ge__(             f.__le__(             f.__rmul__(
f.__class_getitem__(  f.__getattribute__(   f.__len__()           f.__setattr__(
f.__contains__(       f.__getitem__(        f.__lt__(             f.__setitem__(
f.__copy__(           f.__gt__(             f.__mul__(            f.__sizeof__(
f.__delattr__(        f.__hash__            f.__ne__(             f.__str__()
f.__delitem__(        f.__iadd__(           f.__new__(            f.__subclasshook__(
f.__dir__()           f.__imul__(           f.__reduce__(         
f.__doc__             f.__init__(           f.__reduce_ex__(      
```

I will try to implement all of these.

**Comment by blueloveTH** [comment]
Well. Not all of these are needed (for now). Just make an equivalent to our old `deque` implementation.
https://github.com/blueloveTH/pocketpy/blob/main/python/collections.py#L7

Before adding more less-frequently used functions, I need to review the whole structure first and make sure they are of high quality.

Also, you need to write a unittest file to test all your functions you've done, so I recommend to implement a minimum set first.

**Comment by numan947** [comment]
@blueloveTH I think I am ready for the first round of reviews for the code. 

One thing I am not quite sure about is how to add this `deque` class to the previously created `collections` module. Right now, the new `deque` is part of `mycollections` module that  I am creating.

I have added all of the functionalities available in the current implementation of the `deque` available in the `collections` module written in `python`.

I have also added some more functionalities not available in the aforementioned implementation. You can find the newly created "bindings" by search for comments starting with `// NEW:` in the `collections.cpp` file. 

Here's the list of newly added features (see details in [deque documentation](https://docs.python.org/3/library/collections.html#collections.deque)):
1. count(x)
2. extendleft(iterable)
3. index(x[, start[, stop]])
4. insert(i, x)
5. remove(value)
6. reverse()
7. rotate(n=1)
8. maxlen property

Moreover, bounded behavior for append and appendleft is implemented now as I have added the maxlen property.
I will be adding some other functionalities such as addition of two deques, and multiplication operator similar to lists after I write tests for the implemented deque so far.

Please let me know your opinion.

**Comment by blueloveTH** [comment]
I have pushed a commit to rename `mycollections` into `collections` and disable the old python implementation!

**Comment by blueloveTH** [comment]
I added new method `__getnewargs__` to make `deque` support pickle and unpickle.

**Comment by blueloveTH** [comment]
The current implementation is really nice!

However, I want `PyDeque` to be invisible to cpp, that is, the `deque` can only be accessed in python, cpp users are unable to access `PyDeque`.

You need to move the whole `PyDeque` into `collections.cpp`, so the header is only like this:
```cpp
namespace pkpy
{
    void add_module_collections(VM *vm);
} // namespace pkpy
```

Also, since `PyDeque` is invisible, you don't need to provide cpp methods (just inline everything into lambda) unless it is a reusable part that can simplify your code.

**Comment by blueloveTH** [comment]
And there is a method `vm->normalized_index` that handles negative index. You may need to use it?

**Comment by numan947** [comment]
Thanks, I will make the necessary changes and push another commit soon.

**Comment by numan947** [comment]
> The current implementation is really nice!
> 
> However, I want `PyDeque` to be invisible to cpp, that is, the `deque` can only be accessed in python, cpp users are unable to access `PyDeque`.
> 
> You need to move the whole `PyDeque` into `collections.cpp`, so the header is only like this:
> 
> ```c++
> namespace pkpy
> {
>     void add_module_collections(VM *vm);
> } // namespace pkpy
> ```
> 
> Also, since `PyDeque` is invisible, you don't need to provide cpp methods (just inline everything into lambda) unless it is a reusable part that can simplify your code.

So, should I remove all of the member functions of the PyDeque struct (except the constructor) and add the necessary code to the bindings written inside the `_register()` function? I see why we'd want that, it would shorten the code, removing a lot of boiler-platey code.

**Review by blueloveTH — COMMENTED** [review]
You have changed many files, please make sure they are necessary.

For example, you should implement `deque_iterator` in `collections.cpp`, not altering `iter.h`/`iter.cpp` (that's for builtins).

**Comment by numan947** [comment]
@blueloveTH I think I am almost done with this version of the deque and ready for another review. Here's a summary of the files I changed:
1. **collections.h:** header file for the deque
2. **collections.cpp**: contains the deque and deque iterator implementations
3. **70_collections.py**: test file containing code for testing the deque, I have imported the applicable tests from the cpython's `test_deque.py` -- couldn't import all as the current deque implementation doesn't have all the features
4. **amalgamate.py**: you changed it and added collections.h for compiling.
5. **common.h**: added `#include<deque>` so that I don't have to include it every file touch, and it gets included with everything that includes `common.h` 
6. **pocketpy.h**: added the `#include<collections.h>`  to import the collections.h for usage.
7. **vm.h**: There was no support for throwing `RuntimeError` in the current pocketpy implementation. However, deques can throw `RuntimeError` if you write code that can modify the deque during internal iteration (e.g. calling `dq.count()`). Adding a new type of error to throw seemed easy,  so I added it in `vm.h` similar to the other throwable errors.
8. **collections.py & pocketpy.cpp**: You removed the old deque implementation and added the new one.

**Review by blueloveTH — APPROVED** [review]

**Pull request merged**
