### PR TITLE
Datetime file update

### PR DESCRIPTION
**Pull request by MSaiKiran9**
fixes : #140

### CODE REVIEW

**Review by blueloveTH — COMMENTED** [review]
> from datetime import datetime as dt, timedelta as td #internally using datetime , timedelta for __add__,__sub__

I think this is problematic.

```
Traceback (most recent call last):
  File "datetime.py", line 2, in <module>
    from datetime import datetime as dt, timedelta as td #internally using datetime , timedelta for __add__,__sub__
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "datetime.py", line 2, in <module>
    from datetime import datetime as dt, timedelta as td #internally using datetime , timedelta for __add__,__sub__
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'datetime' from partially initialized module 'datetime' (most likely due to a circular import) (datetime.py)
```

**Review by blueloveTH — COMMENTED** [review]
```
    def __eq__(self, other) -> bool:
        return (self.year, self.month, self.day, self.hour, self.minute, self.second) == \
               (other.year, other.month, other.day, other.hour, other.minute, other.second)
```

You may check `other` is a `datetime` instance. If it isn't, return `NotImplemented` otherwise `==` will cause errors.
For all operators, return `NotImplemented` if not supported.

**Comment by MSaiKiran9** [comment]
@blueloveTH  can i inherit the datetime and create the target newclass as required ? can i approach like that ?

**Comment by blueloveTH** [comment]
> @blueloveTH can i inherit the datetime and create the target newclass as required ? can i approach like that ?

Hey. I've checked your code. You don't really need to import it.

There are no rules in python like: "You must define something before use". Python do dynamic lookup.

**Comment by MSaiKiran9** [comment]
but for __add__ & __sub__ we need to write all the implementations if we don't import then right ?

**Comment by blueloveTH** [comment]
> @blueloveTH but for **add** & **sub** we need to write all the implementations if we don't import then right ?

`__add__` and `__sub__` are also functions. I think there are no problem. You can create some test scripts and find how python handles this.

**Comment by MSaiKiran9** [comment]
I'm sorry @blueloveTH i'm a newbie in development . As per my understanding __add__  and  __sub__ takes date/datetime and adds/substracts with timedelta's time and should return new instance of date/datetime right. So if i get it  you're saying to handle date arithmetic directly within our custom classes ? correct me if i'm wrong

**Comment by blueloveTH** [comment]
> I'm sorry @blueloveTH i'm a newbie in development . As per my understanding **add** and **sub** takes date/datetime and adds/substracts with timedelta's time and should return new instance of date/datetime right. So if i get it you're saying to handle date arithmetic directly within our custom class's **add** & **sub** ? correct me if i'm wrong

If you are not sure about `-`/`+` you can directly call `datetime.__add__` or `timedelta.__sub__` and they should be what you have defined exactly.

**Review by blueloveTH — COMMENTED** [review]
You have incorrect understanding! Need to re-check cpython's document.
### `NotImplemented` and `NotImplementedError` are different things!!

> Note NotImplementedError and NotImplemented are not interchangeable, even though they have similar names and purposes. See [NotImplementedError](https://docs.python.org/3/library/exceptions.html#NotImplementedError) for details on when to use it.

```
>>> NotImplemented
NotImplemented
>>>
>>> NotImplementedError
<class 'NotImplementedError'>
```

https://docs.python.org/3/library/constants.html#NotImplemented

The correct usage is:

```python
    def __eq__(self, other: 'timedelta') -> bool:
        if type(other) is not timedelta:
            return NotImplemented  # <-----
        return (self.days, self.seconds) == (other.days, other.seconds)
```

**Pull request merged**
